#theme: minima
remote_theme: jekyll/minima

# Site settings
title: 派猴子来的救兵
email: rmself@qq.com
description:

baseurl: ""
url: "https://ourcat.day"
github_username:  childe

excerpt_separator: <!--more-->
show_excerpts: true
paginate: 10
paginate_path: "/page:num/"

lang: zh-cmn-Hans


plugins:
- jekyll-remote-theme
- jekyll-paginate

google_analytics: UA-56892769-2

minima:
  skin: solarized
  date_format: "%-d %b, %Y"

  header_pages:
    - about.md
  social_links:
    github: childe

author:
  name: childe
  email: "rmself@qq.com"
