theme: minima

# Site settings
title: 派猴子来的救兵
email: heychilde@gmail.com
description:

baseurl: "/ohmycat/"
url: "https://childe.github.io"
github_username:  childe

excerpt_separator: <!--more-->


google_analytics: UA-56892769-2

minima:
  skin: solarized
  date_format: "%-d %b, %Y"

  header_pages:
    - about.md
