# Site settings
title: 派猴子来的救兵
email: heychilde@gmail.com
description: 

baseurl: "/ohmycat/"
url: "https://childe.github.io"
# twitter_username: jekyllrb
github_username:  childe

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
extensions: [fenced_code_blocks]

# paging settings
paginate: 10

gems :
  - jekyll-paginate
