# Site settings
title: 派猴子来的救兵
email: heychilde@gmail.com
description: 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ohmycat.me" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  childe

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
extensions: [fenced_code_blocks]

# paging settings
paginate: 10

gems :
  - jekyll-paginate
