# Site settings
title: 派猴子来的救兵
email: heychilde@gmail.com
description: 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://heychilde.me" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  childe

# Build settings
markdown: redcarpet
extensions: [fenced_code_blocks]
